import SimpleMath as mod
print(mod.__name__)
print(mod.__doc__)
print()
print(mod.addition.__name__)
print(mod.addition.__doc__)
print()
print(mod.subtraction.__name__)
print(mod.subtraction.__doc__)
print()
print(mod.addition(12,7))
print(mod.subtraction(12,7))
